apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: tofui
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.config.encryptionKey | quote }}
  GITHUB_CLIENT_ID: {{ .Values.config.githubClientID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.githubClientSecret | quote }}
  WEBHOOK_SECRET: {{ .Values.config.webhookSecret | quote }}
  S3_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  S3_SECRET_KEY: {{ .Values.minio.auth.rootPassword | quote }}
