// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"encoding/json"
	"time"
)

type Organization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"org_id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	AvatarURL   string    `json:"avatar_url"`
	GithubID    *int64    `json:"github_id"`
	Role        string    `json:"role"`
	LastLoginAt time.Time `json:"last_login_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Workspace struct {
	ID                 string    `json:"id"`
	OrgID              string    `json:"org_id"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	RepoURL            string    `json:"repo_url"`
	RepoBranch         string    `json:"repo_branch"`
	WorkingDir         string    `json:"working_dir"`
	TofuVersion        string    `json:"tofu_version"`
	Environment        string    `json:"environment"`
	AutoApply          bool      `json:"auto_apply"`
	RequiresApproval   bool      `json:"requires_approval"`
	VcsTriggerEnabled  bool      `json:"vcs_trigger_enabled"`
	Locked             bool      `json:"locked"`
	LockedBy           *string   `json:"locked_by"`
	CurrentRunID       *string   `json:"current_run_id"`
	CreatedBy          string    `json:"created_by"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type WorkspaceSummary struct {
	Workspace
	LastRunStatus *string    `json:"last_run_status"`
	LastRunAt     *time.Time `json:"last_run_at"`
	ResourceCount int32     `json:"resource_count"`
}

type Run struct {
	ID               string     `json:"id"`
	WorkspaceID      string     `json:"workspace_id"`
	OrgID            string     `json:"org_id"`
	Operation        string     `json:"operation"`
	Status           string     `json:"status"`
	PlanOutput       string     `json:"plan_output"`
	PlanLogURL       string     `json:"plan_log_url"`
	ApplyLogURL      string     `json:"apply_log_url"`
	ResourcesAdded   int32      `json:"resources_added"`
	ResourcesChanged int32      `json:"resources_changed"`
	ResourcesDeleted int32      `json:"resources_deleted"`
	ErrorMessage     string     `json:"error_message"`
	CommitSHA        string     `json:"commit_sha"`
	PlanJSONURL      string     `json:"plan_json_url"`
	CreatedBy        string     `json:"created_by"`
	StartedAt        *time.Time `json:"started_at"`
	FinishedAt       *time.Time `json:"finished_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type StateVersion struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	OrgID           string    `json:"org_id"`
	RunID           string    `json:"run_id"`
	Serial          int32     `json:"serial"`
	StateURL        string    `json:"state_url"`
	ResourceCount   int32     `json:"resource_count"`
	ResourceSummary string    `json:"resource_summary"`
	CreatedAt       time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         string           `json:"id"`
	OrgID      string           `json:"org_id"`
	UserID     string           `json:"user_id"`
	Action     string           `json:"action"`
	EntityType string           `json:"entity_type"`
	EntityID   string           `json:"entity_id"`
	BeforeData json.RawMessage  `json:"before_data"`
	AfterData  json.RawMessage  `json:"after_data"`
	IPAddress  string           `json:"ip_address"`
	UserAgent  string           `json:"user_agent"`
	CreatedAt  time.Time        `json:"created_at"`
}

type WorkspaceVariable struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	OrgID       string    `json:"org_id"`
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	Sensitive   bool      `json:"sensitive"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
