// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workspaces.sql

package repository

import "context"

const workspaceColumns = `id, org_id, name, description, repo_url, repo_branch, working_dir, tofu_version, environment, auto_apply, requires_approval, vcs_trigger_enabled, locked, locked_by, current_run_id, created_by, created_at, updated_at`

func scanWorkspace(row interface{ Scan(...interface{}) error }) (Workspace, error) {
	var w Workspace
	err := row.Scan(&w.ID, &w.OrgID, &w.Name, &w.Description, &w.RepoURL, &w.RepoBranch, &w.WorkingDir, &w.TofuVersion, &w.Environment, &w.AutoApply, &w.RequiresApproval, &w.VcsTriggerEnabled, &w.Locked, &w.LockedBy, &w.CurrentRunID, &w.CreatedBy, &w.CreatedAt, &w.UpdatedAt)
	return w, err
}

type GetWorkspaceParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx,
		`SELECT `+workspaceColumns+` FROM workspaces WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID,
	)
	return scanWorkspace(row)
}

type ListWorkspacesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+workspaceColumns+` FROM workspaces WHERE org_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`,
		arg.OrgID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var workspaces []Workspace
	for rows.Next() {
		w, err := scanWorkspace(rows)
		if err != nil {
			return nil, err
		}
		workspaces = append(workspaces, w)
	}
	if workspaces == nil {
		workspaces = []Workspace{}
	}
	return workspaces, rows.Err()
}

func (q *Queries) CountWorkspaces(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM workspaces WHERE org_id = $1`, orgID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateWorkspaceParams struct {
	ID                string `json:"id"`
	OrgID             string `json:"org_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	RepoURL           string `json:"repo_url"`
	RepoBranch        string `json:"repo_branch"`
	WorkingDir        string `json:"working_dir"`
	TofuVersion       string `json:"tofu_version"`
	Environment       string `json:"environment"`
	AutoApply         bool   `json:"auto_apply"`
	RequiresApproval  bool   `json:"requires_approval"`
	VcsTriggerEnabled bool   `json:"vcs_trigger_enabled"`
	CreatedBy         string `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO workspaces (id, org_id, name, description, repo_url, repo_branch, working_dir, tofu_version, environment, auto_apply, requires_approval, vcs_trigger_enabled, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		RETURNING `+workspaceColumns,
		arg.ID, arg.OrgID, arg.Name, arg.Description, arg.RepoURL, arg.RepoBranch, arg.WorkingDir, arg.TofuVersion, arg.Environment, arg.AutoApply, arg.RequiresApproval, arg.VcsTriggerEnabled, arg.CreatedBy,
	)
	return scanWorkspace(row)
}

type UpdateWorkspaceParams struct {
	ID                string `json:"id"`
	OrgID             string `json:"org_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	RepoURL           string `json:"repo_url"`
	RepoBranch        string `json:"repo_branch"`
	WorkingDir        string `json:"working_dir"`
	TofuVersion       string `json:"tofu_version"`
	Environment       string `json:"environment"`
	AutoApply         *bool  `json:"auto_apply"`
	RequiresApproval  *bool  `json:"requires_approval"`
	VcsTriggerEnabled *bool  `json:"vcs_trigger_enabled"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE workspaces
		SET name = COALESCE(NULLIF($3, ''), name),
			description = COALESCE(NULLIF($4, ''), description),
			repo_url = COALESCE(NULLIF($5, ''), repo_url),
			repo_branch = COALESCE(NULLIF($6, ''), repo_branch),
			working_dir = COALESCE(NULLIF($7, ''), working_dir),
			tofu_version = COALESCE(NULLIF($8, ''), tofu_version),
			environment = COALESCE(NULLIF($9, ''), environment),
			auto_apply = COALESCE($10, auto_apply),
			requires_approval = COALESCE($11, requires_approval),
			vcs_trigger_enabled = COALESCE($12, vcs_trigger_enabled),
			updated_at = NOW()
		WHERE id = $1 AND org_id = $2
		RETURNING `+workspaceColumns,
		arg.ID, arg.OrgID, arg.Name, arg.Description, arg.RepoURL, arg.RepoBranch, arg.WorkingDir, arg.TofuVersion, arg.Environment, arg.AutoApply, arg.RequiresApproval, arg.VcsTriggerEnabled,
	)
	return scanWorkspace(row)
}

type DeleteWorkspaceParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM workspaces WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID,
	)
	return err
}

func (q *Queries) LockWorkspace(ctx context.Context, id, orgID, lockedBy string) (Workspace, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE workspaces SET locked = TRUE, locked_by = $3, updated_at = NOW()
		WHERE id = $1 AND org_id = $2 AND locked = FALSE
		RETURNING `+workspaceColumns,
		id, orgID, lockedBy,
	)
	return scanWorkspace(row)
}

func (q *Queries) UnlockWorkspace(ctx context.Context, id, orgID string) (Workspace, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE workspaces SET locked = FALSE, locked_by = NULL, updated_at = NOW()
		WHERE id = $1 AND org_id = $2
		RETURNING `+workspaceColumns,
		id, orgID,
	)
	return scanWorkspace(row)
}

type SetWorkspaceCurrentRunParams struct {
	ID           string  `json:"id"`
	OrgID        string  `json:"org_id"`
	CurrentRunID *string `json:"current_run_id"`
}

func (q *Queries) SetWorkspaceCurrentRun(ctx context.Context, arg SetWorkspaceCurrentRunParams) error {
	_, err := q.db.Exec(ctx,
		`UPDATE workspaces SET current_run_id = $3, updated_at = NOW() WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID, arg.CurrentRunID,
	)
	return err
}

func scanWorkspaceSummary(row interface{ Scan(...interface{}) error }) (WorkspaceSummary, error) {
	var ws WorkspaceSummary
	err := row.Scan(
		&ws.ID, &ws.OrgID, &ws.Name, &ws.Description, &ws.RepoURL, &ws.RepoBranch,
		&ws.WorkingDir, &ws.TofuVersion, &ws.Environment, &ws.AutoApply, &ws.RequiresApproval,
		&ws.VcsTriggerEnabled, &ws.Locked, &ws.LockedBy, &ws.CurrentRunID, &ws.CreatedBy,
		&ws.CreatedAt, &ws.UpdatedAt,
		&ws.LastRunStatus, &ws.LastRunAt, &ws.ResourceCount,
	)
	return ws, err
}

type ListWorkspacesWithSummaryParams struct {
	OrgID       string `json:"org_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	Search      string `json:"search"`
	Environment string `json:"environment"`
}

func (q *Queries) ListWorkspacesWithSummary(ctx context.Context, arg ListWorkspacesWithSummaryParams) ([]WorkspaceSummary, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+workspaceColumns+`,
		       lr.status AS last_run_status,
		       lr.created_at AS last_run_at,
		       COALESCE(sv.resource_count, 0) AS resource_count
		FROM workspaces w
		LEFT JOIN LATERAL (
		    SELECT status, created_at FROM runs WHERE workspace_id = w.id ORDER BY created_at DESC LIMIT 1
		) lr ON true
		LEFT JOIN LATERAL (
		    SELECT resource_count FROM state_versions WHERE workspace_id = w.id ORDER BY serial DESC LIMIT 1
		) sv ON true
		WHERE w.org_id = $1
		  AND ($4::TEXT = '' OR w.name ILIKE '%' || $4 || '%')
		  AND ($5::TEXT = '' OR w.environment = $5)
		ORDER BY w.created_at DESC LIMIT $2 OFFSET $3`,
		arg.OrgID, arg.Limit, arg.Offset, arg.Search, arg.Environment,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var workspaces []WorkspaceSummary
	for rows.Next() {
		ws, err := scanWorkspaceSummary(rows)
		if err != nil {
			return nil, err
		}
		workspaces = append(workspaces, ws)
	}
	if workspaces == nil {
		workspaces = []WorkspaceSummary{}
	}
	return workspaces, rows.Err()
}

type CountWorkspacesFilteredParams struct {
	OrgID       string `json:"org_id"`
	Search      string `json:"search"`
	Environment string `json:"environment"`
}

func (q *Queries) CountWorkspacesFiltered(ctx context.Context, arg CountWorkspacesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM workspaces
		WHERE org_id = $1
		  AND ($2::TEXT = '' OR name ILIKE '%' || $2 || '%')
		  AND ($3::TEXT = '' OR environment = $3)`,
		arg.OrgID, arg.Search, arg.Environment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type FindWorkspacesByRepoParams struct {
	RepoURL    string `json:"repo_url"`
	RepoBranch string `json:"repo_branch"`
}

func (q *Queries) FindWorkspacesByRepo(ctx context.Context, arg FindWorkspacesByRepoParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+workspaceColumns+` FROM workspaces
		WHERE LOWER(REGEXP_REPLACE(repo_url, '\.git$', '')) = $1
		AND repo_branch = $2 AND vcs_trigger_enabled = TRUE AND locked = FALSE
		ORDER BY created_at`,
		arg.RepoURL, arg.RepoBranch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var workspaces []Workspace
	for rows.Next() {
		w, err := scanWorkspace(rows)
		if err != nil {
			return nil, err
		}
		workspaces = append(workspaces, w)
	}
	if workspaces == nil {
		workspaces = []Workspace{}
	}
	return workspaces, rows.Err()
}
